---
- name: Repave Pop!_OS
  hosts: popos
  become: true
  vars:
    docker_compose_version: "2.2.2"
    jetbrains_toolbox_version: "1.22.10970"
    kubectl_version: 1.23.0

  tasks:
  - name: Install Apps
    tags: apps
    ansible.builtin.apt:
      name:
      - apt-transport-https
      - code
      - remmina
      - steam
      - zsh
      state: latest
      cache_valid_time: 3600

  - name: Make zsh the users default shell
    tags: shell
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      shell: /usr/bin/zsh

  - name: Downloaded Apps
    tags: 3rd_party_apps
    block:
    - name: Add Google apt signing key
      ansible.builtin.apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Chrome repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome

    - name: Install Google Chrome
      ansible.builtin.apt:
        name: google-chrome-stable
        state: latest
        update_cache: true

    - name: Unpack Jetbrains Toolbox
      ansible.builtin.unarchive:
        src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz
        dest: /tmp
        remote_src: yes

    # - name: Install Jetbrains Toolbox  # apt deb doesn't work either
    #   ansible.builtin.command:
    #     cmd: /tmp/jetbrains-toolbox-{{ jetbrains_toolbox_version }}/jetbrains-toolbox

    - name: Install Google Cloud signing key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repo
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl={{ kubectl_version }}-00
        state: present
        update_cache: true

    - name: Install minikube
      ansible.builtin.apt:
        deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

    - name: Check workstation-linux exists
      ansible.builtin.stat:
        path: /tmp/workstation-linux
      register: workstation_linux

    - name: Download VMware Workstation
      ansible.builtin.get_url:
        url: https://www.vmware.com/go/getworkstation-linux
        dest: /tmp/workstation-linux
        mode: '+x'
      when: workstation_linux.stat.exists == false

    - name: Install VMware Workstation
      ansible.builtin.command:
        cmd: /tmp/workstation-linux --required --eulas-agreed

  - name: Install Python build dependencies
    tags: python
    ansible.builtin.apt:
      name:
      - python3-dev
      - python3-pip
      - python3-venv
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
      state: latest
      cache_valid_time: 3600

  - name: Install Docker Engine
    tags: docker
    block:
    - name: Remove old Docker versions
      ansible.builtin.apt:
        name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
        state: absent

    - name: Install Docker prerequisites
      ansible.builtin.apt:
        name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        state: present
        cache_valid_time: 3600

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu impish stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: latest
        update_cache: true

    - name: Add non-root user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download docker-compose {{ docker_compose_version }}
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: /tmp/docker-compose
        mode: '+x'

    - name: Check docker-compose exists
      ansible.builtin.stat:
        path: /tmp/docker-compose
      register: docker_compose

    - name: Move docker-compose to /usr/local/bin/docker-compose
      ansible.builtin.command:
        cmd: mv /tmp/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists

- name: Repave Pop!_OS non-elevated
  hosts: popos
  become: false

  tasks:
  - name: Configure Python tools
    tags: python
    block:
    - name: Check pyenv
      ansible.builtin.stat:
        path: /home/{{ansible_user}}/.pyenv/bin/pyenv
      register: pyenv_exists

    - name: Run pyenv-installer
      ansible.builtin.shell:
        cmd: curl https://pyenv.run | bash
      when: pyenv_exists.exists is false

    - name: Install pipx
      ansible.builtin.pip:
        name: pipx
        extra_args: --user
        state: latest

    - name: Configure pipx
      ansible.builtin.command:
        cmd: python3 -m pipx ensurepath

    # - name: Install pipx packages
    #   ansible.builtin.shell:
    #     cmd: |
    #       pipx install ansible --include-deps
    #       pipx install bandit
    #       pipx install black
    #       pipx install ipykernel --include-deps
    #       pipx install poetry
    #       pipx install pytest

  - name: Flatpak Apps
    tags: flatpak
    block:
    - name: Install system flatpaks
      community.general.flatpak:
        name:
        - com.bitwarden.desktop
        - org.pulseaudio.pavucontrol
        state: present
        method: user  # Issue with installing system flatpaks. Installing as user instead

    - name: Install user flatpaks
      community.general.flatpak:
        name:
        - com.getpostman.Postman
        - com.microsoft.Teams
        - com.slack.Slack
        - tech.feliciano.pocket-casts
        state: present
        method: user

  - name: Install Oh My Zsh
    tags: shell
    ansible.builtin.shell:
      cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; exit
